### ISSUE TITLE
Omision de patron de diseño Builder

### ISSUE THREAD

**Issue by melpgala** [BryanEstrada003/PROYECTO-2P-G7#2]
Dentro del repositorio 2 se encontró una mala implementación del patron Observer. La interfaz gráfica del programa muestra algo parecido a un observador, pero no lo hace de forma directa en el código. No hay implementación como tal de este patrón para que las clases observables puedan notificar cambios de su estado.

Solución #2: Implementar el patrón de Constructor mediante el uso de un constructor telescópico, constructor de tipo factoría o el patrón de Constructor.
![image](https://github.com/BryanEstrada003/PROYECTO-2P-G7/assets/93047039/d1f3bc90-4039-4d12-8d6f-8487860532bb)

Consecuencias: Con el uso del constructor telescópico el usuario puede elegir entre varios tipos de constructores y así se evita dar valores que no son necesarios. A su vez, mejora la legibilidad del código al usar métodos descriptivos como setYear() en lugar de un constructor con muchos parámetros.

**Comment by BryanEstrada003** [comment]
voy a resolver ese problema
